<a href="https://colab.research.google.com/github/yangjik/yang.study/blob/main/02_%ED%83%80%EC%9D%B4%ED%83%80%EB%8B%89_%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

타이타닉 데이터 분석 처음 할때 한번 보기

https://www.kaggle.com/code/ventureparker/titanic-a-beginner-friendly-approach-to-top-3

In [1]:
import numpy as np
import pandas as pd

In [2]:
# 파일 불러오기
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

### 타이타닉 데이터 구성확인하기

- https://www.kaggle.com/competitions/titanic

In [3]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

PassengerId : <br>
Survived : 생존여부<br>
Pclass : 좌석등급 <br>
Name : 이름 <br>
Sex : 성별 <br>
Age : 나이 <br>
SibSp : 본인기준 자식이랑 동승인지 <br>
Parch : 본인기준 부모님이랑 동승인지 <br>
Ticket : 티켓 <br>
Fare : 요금<br>
Cabin : 선실번호<br>
Embarked : 승선항구(C = 셰르부르, Q = 퀸스타운, S = 사우샘프턴)


아래 정보를 통해서 회귀인지 예측인지 확인 필요
<br>ex) Survived -> 생존 이러한 target데이터

In [4]:
# 전반적인 데이터의 특성 파악
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [5]:
train.shape

(891, 12)

In [6]:
# 클래스 1등실, 2등실, 3등실
train['Pclass'].unique()

array([3, 1, 2])

In [7]:
# Cabin 컬럼의 결측치 파악
train['Cabin'].isnull().sum()

687

## 데이터 전처리

1. 입력(feature) / 타겟(target, label) 정의
2. 적절한 비율로 train, test 데이터 분리.
  - 사용한 패키지 from sklearn.model_selection import train_test_split
  - train_test_split(feature, target, test_size=0.2)
  - test_size=default = 8:2,<br>shuffle : 셔플(섞는 것) default = True,<br>random_state= : 랜덤 시드값 지정


In [8]:
# feature 데이터 정의
feature = train[['Pclass', 'Sex', 'Age', 'Fare']]
feature.head()

Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [9]:
# target 데이터 정의
target = train['Survived']
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [10]:
# train, test 데이터 분리
from sklearn.model_selection import train_test_split

x_train, x_target, y_train, y_target = train_test_split(feature, target, test_size=0.2, random_state=30, shuffle=True)      # 매개변수 순서 X, Y 데이터 그외는 직접 지정, shuffle=True -> default 값이다.

In [11]:
# train, test 비율 확인
x_train.shape, y_train.shape

((712, 4), (712,))

In [12]:
# 데이터 결측치 확인
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [13]:
# Age 의 NaN 값은 나이의 평균값으로 대체
age_mean = train['Age'].mean()
age_mean

29.69911764705882

In [14]:
# NaN 값 평균으로 변경
train['Age'].fillna(age_mean)     # 일반적으로 평균값으로 넣을때는 통계치는 왜곡을 하지않는다.

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...    
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [15]:
# 해당 컬럼 평균값 확인!!
train['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [16]:
# 다른 방법의 결측지 대체 방법.
from sklearn.impute import SimpleImputer

# 평균값으로 채워준다..
imputer = SimpleImputer(strategy='mean')

# imputer = SimpleImputer(strategy='median')          중간
# imputer = SimpleImputer(strategy='most_frequent')   최빈값

In [17]:
# 위에서 평균값을 학습 후 변환시키기
train[['Age']] = imputer.fit_transform(train[['Age']])

In [18]:
# NaN값 확인
train['Age'].isnull().sum()

0

### 결측치 채우는 방법은 두가지가 있다.

1. 해당한 컬럼을 조회한후 .fillna()를 통해서 직접 넣는다.
2. from sklearn.impute import SimpleImputer 패키지를 사용해서 SimpleImputer(Strategy='mean') <- 매소드를 이용해서 평균값, 중간값, 최빈값을 넣는다.


Embarked 결측치 채우기

In [19]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

In [20]:
# Embarked 컬럼 결측치 확인
train['Embarked'].isnull().sum()

2

In [21]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='most_frequent')     # 최빈값

In [22]:
# 데이터는 항상 2차원으로 검색한다.
train[['Embarked']] = imputer.fit_transform(train[['Embarked']])

In [23]:
train['Embarked'].isnull().sum()

0

### 모든 데이터를 수치화 작업!

- 문자 --> 숫자

In [24]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     891 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


방법은 두가지가 있다.

1. for문을 통해서 데이터프레임을 읽고 데이터를 변환
2. from sklearn.preprocessing import LabelEncoder 통해서 변환

In [25]:
# 두번째 방법
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [26]:
# 새로운 컬럼 생성
train['Sex_num'] = le.fit_transform(train['Sex'])

### from sklearn.preprocessing import LabelEncoder 사용법 익히기

- 한번에 2개를 변환은 안된다.

In [27]:
# 레이블 엔코더의 사용법이 아리까리 할때는 간단한 예제 코드를 생성해본다.
from sklearn.preprocessing import LabelEncoder

mylist = ['m', 'f', 'f', 'm', 'f', 'aa', 'bb']
le = LabelEncoder()           # <- Series 데이터를 넣어서 변환을 하는 것이다.

mylist_1 = pd.Series(mylist)
result = le.fit_transform(mylist_1)
result

array([3, 2, 2, 3, 2, 0, 1])

In [28]:
# 레이블 엔코더의 사용법이 아리까리 할때는 간단한 예제 코드를 생성해본다.
from sklearn.preprocessing import LabelEncoder

mylist = pd.Series(['m', 'f', 'f', 'm', 'f', 'aa', 'bb'])
le = LabelEncoder()           # <- Series 데이터를 넣어서 변환을 하는 것이다.

mylist_1 = pd.Series(mylist)
result = le.fit_transform(mylist_1)
result

array([3, 2, 2, 3, 2, 0, 1])

In [29]:
# 0 일땐 어떤것 1일때 어떤것인지 파악
le.classes_

array(['aa', 'bb', 'f', 'm'], dtype=object)

In [30]:
# 변환전 문자열로 확인
le.inverse_transform([0, 1, 1, 0, 0, 1, 1])

array(['aa', 'bb', 'bb', 'aa', 'aa', 'bb', 'bb'], dtype=object)

In [31]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

In [32]:
train['Embarked'] = le.fit_transform(train['Embarked'])

In [33]:
pd.unique(train['Embarked'])        # NaN 값도 하나의 클래스로 분류된다.

array([2, 0, 1, 3])

In [34]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

In [35]:
train['Embarked'].fillna('S', inplace=True)   # NaN 값을 S로 변경후 원본 변화

In [36]:
train['Embarked'].isnull().sum()

0

## 원핫인코딩 (One-hot-encoding)

- 타이타닉 데이터 Embarked 컬럼에서 결과는 S,C,Q 인것을<br>
S C Q<br>
1 0 0<br>
0 1 0<br>
0 0 1<br>
이런식으로 숫자형으로 바꾼다.

In [37]:
train = pd.read_csv('https://bit.ly/fc-ml-titanic')

In [38]:
# Embarked 컬럼에서 S, C, Q 각각 몇개가 있는지 확인
train['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [39]:
# NaN 값 채우기
train['Embarked'] = train['Embarked'].fillna('S')

In [40]:
# 각각의 클래스 개수 파악
train['Embarked'].value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [41]:
# LabelEncoder()를 사용해서 문자데이터 -> 숫자 데이터로 변환한 데이터 새로운 컬럼으로 만들기
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
# fit_transform()  -> 안에 변환할 컬럼 지정
train['Embarked_num'] = le.fit_transform(train['Embarked'])

In [42]:
# S C Q / 2 1 0 으로 개수 확인
train['Embarked_num'].value_counts()

2    646
0    168
1     77
Name: Embarked_num, dtype: int64

In [43]:
# 판다스 패키지 안에 one-hot-encoding 타입으로 변경해주는 함수가있따.
# pd.get_dummies()    <- 여기에 넣을때는 변환한 숫자형데이터를 넣어줘야한다.

## 정규화



In [44]:
# 사전데이터 준비
movie = {'n' : [2, 4, 6, 8, 10],
         'd' : [1, 2, 3, 4, 5]}

In [45]:
# 데이터프레임으로 변환
movie = pd.DataFrame(data=movie)
movie

n  d
0   2  1
1   4  2
2   6  3
3   8  4
4  10  5

사이킷런에 정규화 하는 패키지가 있다.<br>
from sklearn.preprocessing import MinMaxScaler

In [46]:
from sklearn.preprocessing import MinMaxScaler

In [47]:
# defult 값은 0~1 사이로 되어있다.
# 범위를 지정하면 MinMaxScaler(feature_range=(x, y)) x 부터 y 까지

min_max_scaler = MinMaxScaler(feature_range=(0, 5))

In [48]:
min_max_movie = min_max_scaler.fit_transform(movie)

In [49]:
type(min_max_movie)

numpy.ndarray

In [50]:
pd.DataFrame(min_max_movie, columns=['n', 'd'])

n     d
0  0.00  0.00
1  1.25  1.25
2  2.50  2.50
3  3.75  3.75
4  5.00  5.00